name: ci-sonarcloud
on:
  pull_request:
    branches:
      - develop

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - users: actions/checkout@v2
      - uses: actions/setup-node@v3
      with:
        node-version: '18'
      - run: npm test -coverprofile=coverage.out